### ISSUE TITLE
GetStreamLink no working 

### ISSUE THREAD

**Issue by huanx9** [Cyanashi/AutoTaskScripts#1]
Start-Process powershell "<ps1路径> <播放器路径> <直播间>"

为什么我执行了 没动静阿 。

**Comment by huanx9** [comment]
版本 1.0.6  之前没试过命令行的方式

**Comment by Cyanashi** [comment]
用法是正确的，我这里测试 v1.0.6 也没问题。
如果同样的播放器路径和直播间地址，用其他的方法没问题的话，应该是脚本路径有问题吧。
确定 `<ps1路径>` 是有效路径吗，完整的绝对路径 `X:\文件夹\文件名.ps1` 或者相对路径 `.\文件名.ps1` ？

**Comment by huanx9** [comment]
Start-Process powershell "C:\live.ps1 C:\Potplayer\PotPlayerMini64.exe https://www.douyu.com/12345"

你看一下我的案例  哪里有问题 .  

用powershell启动  窗口一闪而过..

**Comment by Cyanashi** [comment]
用法没问题，命令行窗口一闪而过应该是脚本有问题，或者你试试 `$psversiontable.psversion` 看看 ps 版本，我开发 / 测试的版本都是 5.1，没有对在此之前的版本做过兼容。  
![示例](https://i.loli.net/2020/04/03/fmPMw8HhirC7pAR.gif)

**Comment by huanx9** [comment]
我刚解决了这个BUG 。
由于系统默认使用的策略为`restricted`
所以
set-executionpolicy remotesigned
切换策略
就可以执行第三方没有签证的 PS1脚本了。

**Comment by huanx9** [comment]
不能说是BUG吧。 总之是解决了这个问题。 感谢开发者。
